apiVersion: v2
name: airia-test-pod
description: A Helm chart for Airia Infrastructure Test Pod - validates customer infrastructure readiness
type: application
version: 1.0.191
appVersion: "1.0.191"
keywords:
- infrastructure
- testing
- validation
- azure
- kubernetes
home: https://github.com/airia/test-pod
sources:
- https://github.com/airia/test-pod
maintainers:
- name: Airia Team
  email: support@airia.com

dependencies:
- name: ingress-nginx
  version: "4.11.3"
  repository: https://kubernetes.github.io/ingress-nginx
  condition: ingress-nginx.enabled