apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airia-test-pod
  namespace: airia
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
  # Host 1
  - host: test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airia-test-pod
            port:
              number: 80
  # Host 2
  - host: readiness.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airia-test-pod
            port:
              number: 80
  # Host 3
  - host: infra-test.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airia-test-pod
            port:
              number: 80
  # Host 4
  - host: validation.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airia-test-pod
            port:
              number: 80
  # Host 5
  - host: precheck.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: airia-test-pod
            port:
              number: 80
  tls:
  - hosts:
    - test.example.com
    - readiness.example.com
    - infra-test.example.com
    - validation.example.com
    - precheck.example.com
    secretName: airia-test-pod-tls